### ISSUE TITLE
search by multiple filters

### ISSUE THREAD

**Issue by asaletourneau** [Conal-Tuohy/Provisualizer#7] opened 2015-03-04 02:48 UTC
This was pre-empted in an earlier email. After testing today it re-occurred to me that the user will probably need to search by keyword and date.

**Comment by Conal-Tuohy** [comment] 2015-03-04 02:51
Is this a duplicate of #1 ?

**Comment by asaletourneau** [comment] 2015-03-04 03:06
Hi,

Just sent an email regarding this issue to you're gmail address. It says:

"Hi Conal,

Re  the most recent issue I raised on github, just wanted to forward the 
below  email because I don't want you to think I'm just raising new 
issues. Please see item 4 below from Feb correspondence. 
I'm just mindful of the fact you're working hard on this and I don't want 
you to think I'm just sitting here coming up  with new issues just because 
there's a github repository to use. The item 4 reads:

4. A filter search by keyword (across all Function and Agency titles) and 
date (if year and  range is at all possible that would be great but I'll 
settle for whatever is actually feasible).

Thanks.

BTW, I just printed out that fantastic comment from Archival Access that I 
will proudly display on my desk!
:)"



Asa Letourneau
Project Officer ,Communications and Online Transformation, Public Record 
Office Victoria
03 9348 5759 I  0423 482 127 I  fax 03 9348 5656
asa.letourneau@prov.vic.gov.au

Please note I work from home on Mondays


 
Sailing into Melbourne exhibition, Old Treasury Building | 
http://www.oldtreasurybuilding.org.au
walata tyamateetj exhibition, Victorian Archives Centre | 
http://prov.vic.gov.au/whats-on/exhibitions
Research the Collection | http://prov.vic.gov.au/research

You must not copy, disclose, distribute, store or otherwise use this 
material without permission. Any personal information in this email must 
be handled in accordance with the Information Privacy Act 2000 (Vic) and 
applicable laws. If you are not the intended recipient, please notify the 
sender immediately and destroy all copies of this email and any 
attachments. The State does not accept liability in connection with 
computer viruses, data corruption, delay, interruption, unauthorised 
access or use.

**Closed** 2015-03-04 06:35 UTC

**Comment by asaletourneau** [comment] 2015-03-06 01:12
So bloody excited now. PROV should have done this 10 years ago. I love what you've done including the layout which is genius. The only minor tweak I'd make is to change 'Enter agency or function name:' to 'Enter a keyword:' My reason is that first time users may be freaked out by not knowing a Function or Agency name but everyone knows how to enter a keyword thanks to Google. Apart from that you are bloody brilliant and I can't wait to see the remaining functionality added, especially the Share tab!
